### PR TITLE
WorldEdit command listener fixes

### PR DESCRIPTION
**Pull request by SomewhatDisoriented**
- Case insensitive command filter
- Catch /up which is an alias of //up

### CODE REVIEW

**Comment by jomo** [comment]
Weird, I already did this – and a few more improvements – in #15.
Apparently it was reverted at some point

**Comment by jomo** [comment]
Note my comment in #15, apparently I already noticed it was gone somehow :confused:

**Comment by SomewhatDisoriented** [comment]
Yeah, that's odd. :o Your approach is definitely better, hopefully Matt can add it back into the project. :)

**Comment by jomo** [comment]
Yup, but make sure `/repl` is included, I missed that one.

**Comment by SomewhatDisoriented** [comment]
To add to that, it would be nice if the lists of disabled and restricted commands were added to the config. It would be useful for servers that use a plugin called AsyncWorldEdit and its extension AsyncWorldEdit-PlotMeCore* which makes most (if not all?) WorldEdit commands compatible with PlotMe-Core.

**Comment by MattBDev** [comment]
WorldEdit was fixed in the refractor-0.17 branch. I will not be merging this but I appreciate the help. 
32e1853a202abb56ac52d50d03a5134b72357f69 Feel free to check if I messed something up.
:smiley:

**Comment by jomo** [comment]
@MattBDev I assume [PlotMeWorldEdit](https://github.com/WorldCretornica/PlotMe-Core/blob/9ab980a6856350b40418caf887b0344d92e20d71/src/bukkit/java/com/worldcretornica/plotme_core/bukkit/PlotMeWorldEdit.java) takes care of only changing blocks where allowed, so it doesn't rely on gmask anymore? If so, that's awesome as `/gmask` could be allowed to players without the risk of causing changes outside their plots :smile:

**Comment by MattBDev** [comment]
@jomo That's exactly what it means. I have to look into compatibility with asyncworldedit though.

**Pull request closed without merging**
