### PR TITLE
Thoughts?

### PR DESCRIPTION
**Pull request by ItsHarry**
Don't merge this, I just want you guys @ZachBora @MattBDev to take a look at what I did to the isPlotAvailable() command. Basically, it uses a simpler SQL query, which should speed it up by a ton.

Tell me what you think. I really want /plot auto fixed

PS: Don't pay attention to the 3 other commits, and all the other stuff I have changed. The only important stuff is isPlotAvailable() and SqlManager.exists()

### CODE REVIEW

**Comment by MattBDev** [comment]
@ItsHarry I am planning on rewriting all the SQL code so plot auto is fixed but I do understand what you are doing.

**Comment by ItsHarry** [comment]
Okay, do you have an ETA to when the command will be fixed?

**Comment by MattBDev** [comment]
I don't like giving ETA's anymore but it I am working on it as I type this message

**Comment by ItsHarry** [comment]
Alright, let me know if there's anything you need help with

**Pull request closed without merging**
