### PR TITLE
Cache UUID and also fix NPE

### PR DESCRIPTION
**Pull request by ItsHarry**
See title/changes

### CODE REVIEW

**Comment by ItsHarry** [comment]
Could you pull this as soon as possible? I need the NPE to be fixed in PlayerInteractEvent, but since I get an error after compiling, I need Jenkins build =)

**Comment by ItsHarry** [comment]
Nevermind, it's working now. I guess it's because I was using an outdated PlotMe-DefaultGenerator? makes no sense lol

**Comment by MattBDev** [comment]
I would accept this but I rather let ZachBora make the decision. The worldedit fix is something we will change guaranteed.

**Comment by ZachBora** [comment]
looks good

**Pull request merged**
